source "https://rubygems.org"

gem "lita"

# Uncomment to use the HipChat adapter
gem "lita-hipchat"

# Uncomment to use the Slack adapter
# gem "lita-slack"

# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"

gem "lita-xl-deploy", :path => "../lita-xl-deploy"
